NameOfChest: 'CustomChest'
Command: '/chest'
PriceOfRow1: 255.0
PriceOfRow2: 300.0
PriceOfRow3: 500.0
PriceOfRow4: 800.0
PriceOfRow5: 900.0
PriceOfRow6: 1200.0

NumberOfRow: 3

PermissionMessage: 'Not Enought Permission'
Prefix: '[CustomChest]'
EnablePrefix: true
NotEnoughtMoney: 'You dont have enought money to buy this'
BoughtRowMessage: 'You just bought a row in your chest'

UseAsEnderChest: false

 